filebeat.inputs:
  - type: filestream
    id: docker-filestream
    enabled: true
    paths:
      - ingest_data/*.log
      - /var/lib/docker/containers/*/*.log
      - /docker_network_logs/*/*.log
      # - /var/log/*.log


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: ""
          config:
            - type: container
              stream: stdout
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash01:5044"]
